version: "3"

services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data